/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface SlotChild {
    }
    interface SlotParent {
        "searchedFor": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSlotChildElement extends Components.SlotChild, HTMLStencilElement {
    }
    var HTMLSlotChildElement: {
        prototype: HTMLSlotChildElement;
        new (): HTMLSlotChildElement;
    };
    interface HTMLSlotParentElement extends Components.SlotParent, HTMLStencilElement {
    }
    var HTMLSlotParentElement: {
        prototype: HTMLSlotParentElement;
        new (): HTMLSlotParentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "slot-child": HTMLSlotChildElement;
        "slot-parent": HTMLSlotParentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface SlotChild {
    }
    interface SlotParent {
        "searchedFor"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "slot-child": SlotChild;
        "slot-parent": SlotParent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "slot-child": LocalJSX.SlotChild & JSXBase.HTMLAttributes<HTMLSlotChildElement>;
            "slot-parent": LocalJSX.SlotParent & JSXBase.HTMLAttributes<HTMLSlotParentElement>;
        }
    }
}
